name: dart_firebase_admin
description: A Firebase Admin SDK implementation for Dart.
version: 0.3.0
homepage: "https://github.com/invertase/dart_firebase_admin"
repository: "https://github.com/invertase/dart_firebase_admin"

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  dart_jsonwebtoken: ^2.11.0
  firebaseapis: ^0.2.0
  freezed_annotation: ^2.4.1
  googleapis_auth: ^1.3.0
  http: ^1.0.0
  intl: ^0.19.0
  meta: ^1.9.1
  pointycastle: ^3.7.4

dev_dependencies:
  build_runner: ^2.4.7
  file: ^7.0.0
  freezed: ^2.4.2
  mockito: ^5.4.3
  mocktail: ^1.0.1
  test: ^1.24.4
  uuid: ^4.0.0
