name: dart_firebase_admin
description: A Firebase Admin SDK implementation for Dart.
version: 0.4.1
homepage: "https://github.com/invertase/dart_firebase_admin"
repository: "https://github.com/invertase/dart_firebase_admin"

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  asn1lib: ^1.6.0
  collection: ^1.18.0
  dart_jsonwebtoken: ^3.0.0
  freezed_annotation: ^3.0.0
  googleapis: ^13.2.0
  googleapis_auth: ^1.3.0
  googleapis_beta: ^9.0.0
  http: ^1.0.0
  intl: ^0.20.0
  jose: ^0.3.4
  meta: ^1.9.1
  pem: ^2.0.5
  pointycastle: ^3.7.0

dev_dependencies:
  build_runner: ^2.4.7
  file: ^7.0.0
  freezed: ^3.0.0
  mocktail: ^1.0.1
  path: ^1.9.1
  test: ^1.24.4
  uuid: ^4.0.0

false_secrets:
 - /test/auth/jwt_test.dart
 - /test/client/get_id_token.js