name: dart_firebase_admin_example
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.13.2
  dart_firebase_admin:
    path: ../
  firebase_core: ^2.23.0
  flutter:
    sdk: flutter
