name: googleapis_dart_storage
description: Dart client for Gogole Cloud Storage - unified object storage for developers and enterprises, from live data serving to data analytics/ML to data archiving.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.2.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
